# Generated by Django 3.0.8 on 2020-07-10 02:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0002_auto_20200710_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecolumn',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 2, 10, 32, 981462, tzinfo=utc)),
        ),
    ]
