# Generated by Django 3.0.8 on 2020-07-10 02:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0005_auto_20200710_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecolumn',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 2, 33, 12, 907685, tzinfo=utc)),
        ),
    ]
