# Generated by Django 3.0.8 on 2020-07-10 02:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_auto_20200710_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 2, 18, 36, 399072, tzinfo=utc)),
        ),
    ]
