# Generated by Django 3.0.8 on 2020-07-10 02:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0007_auto_20200710_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 2, 40, 11, 893220, tzinfo=utc)),
        ),
    ]
